[Global]
FallbackTheme=_fallback

[Common]
# How big the design of the theme is. for example, if a theme was designed for
# 1080p, it would be shrunken for 640x480, as well as that, if it was designed
# for 480p, it would be enlarged for bigger screens!
ScreenWidth=1
ScreenHeight=720

# Allows you to pick all available game modes for your gametype: for example,
# inserting enough coins for 1p would let you choose between solo, single
# and double before each game
AutoSetStyle=true

# Default modifiers and noteskin.
DefaultModifiers="C400"
DefaultNoteSkinName="Default"

# Screens that show over everything else.
# Only mess with this if you know what you're doing.
OverlayScreens="ScreenSystemLayer,ScreenSyncOverlay,ScreenStatsOverlay,ScreenDebugOverlay,ScreenInstallOverlay,ScreenChatOverlay,ScreenToolTipOverlay"

# We want to define which Images to cache.
# Predefined Images include: Banner,Background,CDTitle,Jacket,CDImage,Disc
# Is Case Sensitive
ImageCache="Banner"

[SongManager]
NumSongGroupColors=1
SongGroupColor1=color("#CCCCCC")
ExtraColor=color("#CCCCCC")

[MusicWheel]
NumSectionColors=1
SectionColor1=color("#CCCCCC")
FadeSeconds=1
SwitchSeconds=0.10
RandomPicksLockedSongs=true
UseSectionsWithPreferredGroup=false
OnlyShowActiveSection=false
HideActiveSectionTitle=true
RemindWheelPositions=false
#
RouletteSwitchSeconds=0.05
RouletteSlowDownSwitches=5
LockedInitialVelocity=15

ScrollBarHeight=SCREEN_HEIGHT
ScrollBarOnCommand=visible,true;xy,-20,0;zoomx,0.2;zoomy,0.8;diffuse,COLOR.MainHighlight;diffusealpha,0.8;
#
#ItemTransformFunction=function(self,offsetFromCenter,itemIndex,numItems) self:x( (1-math.cos(offsetFromCenter/math.pi))*44 ); self:y( offsetFromCenter*38 ); end
ItemTransformFunction=function(self,offsetFromCenter,itemIndex,numItems) self:x(0):y( offsetFromCenter*44):diffusealpha(math.min(1,1.8-math.abs(offsetFromCenter)/5)); end
NumWheelItems=16

ShowRoulette=false

[MusicWheelItem]

SongNameX=30
SongNameOnCommand=
SongNameSetCommand=%function(self,param) local title = self:GetChild("Title"); local artist = self:GetChild("Artist"); ApplyRawMSDColor(title, param and param.Song); ApplyRawMSDColor(artist, param and param.Song) end
CourseX=30
CourseY=-3
CourseOnCommand=

SectionExpandedX=50
SectionExpandedY=0
SectionExpandedOnCommand=zoom,0.6;halign,0;maxwidth,capWideScale(get43size(280),280)/0.6;
SectionCollapsedX=50
SectionCollapsedY=0
SectionCollapsedOnCommand=zoom,0.6;halign,0;maxwidth,capWideScale(get43size(280),280)/0.6;
SectionCountX=15
SectionCountY=0
SectionCountOnCommand=zoom,0.40;diffuse,COLOR.MainBackground;

SortX=10
SortY=0
SortOnCommand=zoom,0.875;halign,0;stopeffect;maxwidth,capWideScale(get43size(290),290)/0.875;

WheelNotifyIconX=215
WheelNotifyIconY=-7
WheelNotifyIconOnCommand=zoom,0.40;diffusealpha,0.4;


[TextBanner]
TitleOnCommand=halign,0;diffuse,color("#FFFFFF");
SubtitleOnCommand=diffusealpha,0;
ArtistOnCommand=halign,0;diffuse,color("#FFFFFF");
ArtistPrependString="// "

[ScreenWithMenuElements]
ShowHeader = true
ShowFooter = true
HeaderX =
FooterX = 
HeaderY = 
FooterY =

[ScreenSelectMusic]
MusicWheelX=20
MusicWheelY=SCREEN_CENTER_Y+20
MusicWheelOnCommand=
MusicWheelOffCommand=stoptweening;sleep,0.5;smooth,0.2;diffusealpha,0;

SampleMusicPreviewMode="SampleMusicPreviewMode_ScreenMusic"
SampleMusicLoops=true
SampleMusicFallbackFadeInSeconds=0
SampleMusicFadeOutSeconds=1.5

[ScreenChartPreview]
Class="ScreenWithMenuElements"
Fallback="ScreenWithMenuElements"
PrevScreen="ScreenSelectMusic"
PlayMusic=false

[ScreenToolTipOverlay]
Class="ScreenWithMenuElements"
Fallback="Screen"

TimerSeconds=-1
FirstUpdateCommand=
PlayMusic=false
MusicAlignBeat=true
DelayMusicSeconds=0
StopMusicOnBack=false
WaitForChildrenBeforeTweeningOut=false
CancelTransitionsOut=false
ShowCreditDisplay=true
AllowDisabledPlayerInput=false
TimerStealth=true
ForceTimer=false
TimerMetricsGroup="MenuTimer"
TimerX=
TimerY=
TimerOnCommand=
TimerOffCommand=

[ScreenEvaluation]
Class="ScreenEvaluation"
Fallback="ScreenWithMenuElements"
HeaderTitle="Evaluation"
NextScreen="ScreenSelectMusic"

[ScreenInit]
Class="ScreenWithMenuElements"
Fallback="ScreenWithMenuElements"
ShowHeader=false
ShowFooter=false
ShowBackground=false
ShowCreditDisplay=false
NextScreen="ScreenTitleMenu"
TimerSeconds=2.5

[ScreenPlayerOptions]
Class="ScreenPlayerOptions"
Fallback="ScreenOptions"
HeaderTitle="Player Options"
ShowHeader=true
NextScreen="ScreenStageInformation"

[ScreenSongOptions]
Class="ScreenSongOptions"
Fallback="ScreenOptions"
NextScreen="ScreenStageInformation"

[ScreenOptionsMaster]
Class="ScreenOptionsMaster"
Fallback="ScreenOptions"
HeaderTitle="Options"
ShowHeader=true

[ScreenOptionsService]
Class="ScreenOptionsMaster"
Fallback="ScreenOptionsSimpleService"
HeaderTitle="Options"
ShowHeader=true
AllowOperatorMenuButton=false
NextScreen=Branch.AfterInit()
PrevScreen=Branch.AfterInit()
LineNames="GraphicSound,KeyConfig,Theme,InputOptions,SoundGraphics,Profiles,Network,Advanced"
LineSync="gamecommand;screen,ScreenGameplaySyncMachine;name,Calibrate Machine Sync"
LineGameType="gamecommand;screen,ScreenSelectGame;name,Select Game"
LineKeyConfig="gamecommand;screen,ScreenMapControllers;name,Key Joy Mappings"
LineInput="gamecommand;screen,ScreenOptionsInput;name,Input Options"
LineTheme="gamecommand;screen,ScreenOptionsTheme;name,Theme Options"
LineGraphicSound="gamecommand;screen,ScreenOptionsGraphicsSound;name,Graphics/Sound Options"
LineProfiles="gamecommand;screen,ScreenOptionsManageProfiles;name,Profiles"
LineNetwork="gamecommand;screen,ScreenNetworkOptions;name,Network Options"
LineAdvanced="gamecommand;screen,ScreenOptionsAdvanced;name,Advanced Options"
LineSoundGraphics="gamecommand;screen,ScreenOptionsDisplaySub;name,Display Options"
LineInputOptions="gamecommand;screen,ScreenOptionsInputSub;name,InputOptions"
RowInitCommand=stoptweening
RowOnCommand=stoptweening
RowOffCommand=stoptweening
ShowScrollBar=false
ScrollBarHeight=0
ScrollBarTime=0
LineHighlightX=SCREEN_CENTER_X
ShowExplanations=false
AllowRepeatingChangeValueInput=true
CursorTweenSeconds=0.15
WrapValueInRow=false
OptionRowExitMetricsGroup="OptionRowExit"
PageX=SCREEN_CENTER_X
PageY=SCREEN_CENTER_Y
PageOnCommand=stoptweening
ContainerOnCommand=stoptweening
MoreX=SCREEN_CENTER_X
MoreY=SCREEN_CENTER_Y

[ScreenSelectGame]
Class="ScreenOptionsMaster"
Fallback="ScreenOptions"
HeaderTitle="Options"
ShowHeader=true

[ScreenMapControllers]
Class="ScreenMapControllers"
Fallback="ScreenOptionsServiceChild"
ListHeaderGainFocusCommand=diffuse,color("0,0,0,1");stopeffect
MappedToGainFocusCommand=diffuse,color("0,0,0,1");stopeffect
MappedToMappedInputCommand=diffuse,color("0,0,0,1");stopeffect
MappedToLoseFocusCommand=diffuse,color("0.5,0.5,0.5,1");stopeffect

[OptionRowService]
Fallback="OptionRow"
ColorSelected=color("0,0,0,1")
TitleGainFocusCommand=diffuse,color("0,0,0,1");strokecolor,color("0,0,0,1")

[OptionRow]
ColorSelected=color("0,0,0,1")
TitleGainFocusCommand=diffuse,color("0,0,0,1");strokecolor,color("0,0,0,1")

[ScreenOptionsSimpleService]
Fallback="ScreenOptionsSimple"
OptionRowNormalMetricsGroup="OptionRowService"
LineHighlightP1OnCommand=visible,false
LineHighlightP2OnCommand=visible,false
CursorOnCommand=visible,false

[ScreenGameplay]
ShowHeader=false
ShowFooter=false
ShowBackground=false

[ScreenStageInformation]
Class="ScreenWithMenuElements"
Fallback="ScreenWithMenuElements"
ShowHeader=false
ShowFooter=false
ShowBackground=false
NextScreen="ScreenGameplay"
TimerSeconds=-1
TimerStealth=true
ForceTimer=true
TimerMetricsGroup="MenuTimer"
WaitForChildrenBeforeTweeningOut=false
CancelTransitionsOut=false


[ScreenTitleMenu]
HeaderTitle="Welcome Back"
ShowHeader=true

ChoiceX=SCREEN_WIDTH - 20
ChoiceY=SCREEN_CENTER_Y + 20
ChoiceTransformFunction=function(self,offset,itemIndex,numItems) self:x(0):y((itemIndex - (numItems-1)/2) * 50):halign(1):diffuse(color("#000000")):diffusealpha(1) end
ScrollerX=SCREEN_WIDTH - 20
ScrollerY=SCREEN_CENTER_Y + 20
ScrollerTransform=function(self,offset,itemIndex,numItems) self:x(0):y((itemIndex - (numItems-1)/2) * 50) end
